[build]
  command = "rm -rf package-lock.json node_modules && npm install && npm run build"
  publish = "dist"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200